In [98]:
from sklearn.preprocessing import normalize
from mvpa2.suite import *
import ni_nileUtils

[tempHistorical, models] = ni_nileUtils.readModelData('data/r1-temp-historical.csv')
[prHistorical, models] = ni_nileUtils.readModelData('data/r1-pr-historical.csv')

som = SimpleSOMMapper((2,2), 3000, learning_rate=0.01)

inds = range(12,np.size(tempHistorical['gfdl-cm3']))

data = []

for i in inds:
    data.append([tempHistorical['gfdl-cm3'][i], prHistorical['gfdl-cm3'][i]])

data = np.array(data)
data = normalize(data,axis=0)

som.train(data)

#pl.imshow(som.K, origin='lower')


#mapped = som(colors)

#pl.title('Color SOM')
# SOM's kshape is (rows x columns), while matplotlib wants (X x Y)
#for i, m in enumerate(mapped):
#    pl.text(m[1], m[0], color_names[i], ha='center', va='center',
#           bbox=dict(facecolor='white', alpha=0.5, lw=0))


# show the figure
#pl.show()


In [99]:
import collections

print(data[:,0].max())
print(data[:,1].max())

mapped=[(x[0],x[1]) for x in som(data)]
print(som.K)
c = collections.Counter(mapped)
print(c)


0.0709769416225
0.243900716149
[[[ 0.05604282  0.01648312]
  [ 0.0517898   0.03581307]]

 [[ 0.0541877   0.03590967]
  [ 0.04236407  0.06990439]]]
Counter({(0, 0): 202, (1, 1): 81, (0, 1): 47, (1, 0): 18})


In [102]:
from sklearn.preprocessing import normalize
from mvpa2.suite import *
import ni_nileUtils

[tempHistorical, models] = ni_nileUtils.readModelData('data/r1-temp-rcp45.csv')
[prHistorical, models] = ni_nileUtils.readModelData('data/r1-pr-rcp45.csv')

som = SimpleSOMMapper((2,2), 3000, learning_rate=0.01)

inds = range(12,np.size(tempHistorical['gfdl-cm3']))

data = []

for i in inds:
    data.append([tempHistorical['gfdl-cm3'][i], prHistorical['gfdl-cm3'][i]])

data = np.array(data)
data = normalize(data,axis=0)

som.train(data)

#pl.imshow(som.K, origin='lower')


#mapped = som(colors)

#pl.title('Color SOM')
# SOM's kshape is (rows x columns), while matplotlib wants (X x Y)
#for i, m in enumerate(mapped):
#    pl.text(m[1], m[0], color_names[i], ha='center', va='center',
#           bbox=dict(facecolor='white', alpha=0.5, lw=0))


# show the figure
#pl.show()


In [103]:

print(data[:,0].max())
print(data[:,1].max())

mapped=[(x[0],x[1]) for x in som(data)]
print(som.K)
c = collections.Counter(mapped)
print(c)


0.0410464467959
0.218488311476
[[[ 0.03185142  0.00756808]
  [ 0.03056055  0.01663213]]

 [[ 0.03180824  0.0167085 ]
  [ 0.02554913  0.03792811]]]
Counter({(0, 0): 626, (1, 1): 237, (0, 1): 159, (1, 0): 46})


In [100]:
from sklearn.preprocessing import normalize
from mvpa2.suite import *
import ni_nileUtils

[tempHistorical, models] = ni_nileUtils.readModelData('data/r1-temp-rcp85.csv')
[prHistorical, models] = ni_nileUtils.readModelData('data/r1-pr-rcp85.csv')

som = SimpleSOMMapper((2,2), 3000, learning_rate=0.01)

inds = range(12,np.size(tempHistorical['gfdl-cm3']))

data = []

for i in inds:
    data.append([tempHistorical['gfdl-cm3'][i], prHistorical['gfdl-cm3'][i]])

data = np.array(data)
data = normalize(data,axis=0)

som.train(data)

#pl.imshow(som.K, origin='lower')


#mapped = som(colors)

#pl.title('Color SOM')
# SOM's kshape is (rows x columns), while matplotlib wants (X x Y)
#for i, m in enumerate(mapped):
#    pl.text(m[1], m[0], color_names[i], ha='center', va='center',
#           bbox=dict(facecolor='white', alpha=0.5, lw=0))


# show the figure
#pl.show()


In [101]:

print(data[:,0].max())
print(data[:,1].max())

mapped=[(x[0],x[1]) for x in som(data)]
print(som.K)
c = collections.Counter(mapped)
print(c)


0.0436039149096
0.218488311476
[[[ 0.02600844  0.03800006]
  [ 0.03169792  0.01664206]]

 [[ 0.03288395  0.01668168]
  [ 0.03298357  0.00759128]]]
Counter({(1, 1): 624, (0, 0): 240, (0, 1): 165, (1, 0): 39})
